spring:
  application:
    name: user-access-policy-ingestion

  datasource:
    url: jdbc:postgresql://localhost:5432/user_access_policy_ingestion
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    sql:
      init:
        mode: never

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: policy-group
      auto-offset-reset: earliest


  # kafka:
  #   bootstrap-servers: localhost:9092
  #   consumer:
  #     group-id: policy-group
  #     auto-offset-reset: earliest
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #   consumer:
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  #     properties:
  #       spring.json.trusted.packages: "*"