name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    #isolated PostgreSQL db on the gh server
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.APP_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.APP_DB_PASSWORD }}
          POSTGRES_DB: user_access_policy_ingestion
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #install java on gh runner
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      #Install postman CLI tool
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      #start java app in the background using creds
      - name: Start Spring Boot Application
        working-directory: ./user-access-policy-ingestion 
        env:
          APP_DB_USER: ${{ secrets.APP_DB_USER }}
          APP_DB_PASSWORD: ${{ secrets.APP_DB_PASSWORD }}
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/user_access_policy_ingestion
        run: |
          ./mvnw spring-boot:run > spring-boot.log 2>&1 &
          echo "Waiting for application to start..."
          sleep 15

      #authenticate postman
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      #run tests
      - name: Run API tests
        env:
          APP_DB_USER: ${{ secrets.APP_DB_USER }}
          APP_DB_PASSWORD: ${{ secrets.APP_DB_PASSWORD }}
        run: |
          postman collection run "45007541-53eb88f3-fbc2-4df6-a81b-fa5d09e1c767"
      
      #runs this step if the Postman tests fail
      - name: Print Spring Boot Application Logs on Failure
        if: failure()
        run: |
          echo "=== SPRING BOOT RECENT LOGS ==="
          cat spring-boot.log || echo "No log file found."